version: '2'
services:
    myfirstmonolithicapp-app:
        image: myfirstmonolithicapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://myfirstmonolithicapp-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=MyFirstMonolithicApp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8090:8090
    myfirstmonolithicapp-mongodb:
        extends:
            file: mongodb.yml
            service: myfirstmonolithicapp-mongodb
